name: build

on:
  - push

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Java setup
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: 8
          cache: "gradle"

      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Build
        run: |
          @if "%DEBUG%" == "" @echo off
          if "%OS%"=="Windows_NT" setlocal
          set DIRNAME=%~dp0
          if "%DIRNAME%" == "" set DIRNAME=.
          set APP_BASE_NAME=%~n0
          set APP_HOME=%DIRNAME%
          set DEFAULT_JVM_OPTS=
          if defined JAVA_HOME goto findJavaFromJavaHome
          set JAVA_EXE=java.exe
          %JAVA_EXE% -version >NUL 2>&1
          if "%ERRORLEVEL%" == "0" goto init
          goto fail
          :findJavaFromJavaHome
          set JAVA_HOME=%JAVA_HOME:"=%
          set JAVA_EXE=%JAVA_HOME%/bin/java.exe
          if exist "%JAVA_EXE%" goto init
          goto fail
          :init
          if not "%OS%" == "Windows_NT" goto win9xME_args
          :win9xME_args
          set CMD_LINE_ARGS=
          set _SKIP=2
          :win9xME_args_slurp
          if "x%~1" == "x" goto execute
          set CMD_LINE_ARGS=%*
          :execute
          set CLASSPATH=%APP_HOME%\gradle\wrapper\gradle-wrapper.jar
          "%JAVA_EXE%" %DEFAULT_JVM_OPTS% %JAVA_OPTS% %GRADLE_OPTS% "-Dorg.gradle.appname=%APP_BASE_NAME%" -classpath "%CLASSPATH%" org.gradle.wrapper.GradleWrapperMain %CMD_LINE_ARGS%
          :end
          if "%ERRORLEVEL%"=="0" goto mainEnd
          :fail
          rem Set variable GRADLE_EXIT_CONSOLE if you need the _script_ return code instead of
          rem the _cmd.exe /c_ return code!
          if  not "" == "%GRADLE_EXIT_CONSOLE%" exit 1
          exit /b 1
          :mainEnd
          if "%OS%"=="Windows_NT" endlocal
          :omega

      - name: Rename build artifacts
        run: mv build/libs/FDPClient-*.jar build/libs/FDPClient-${{ steps.vars.outputs.sha_short }}.jar

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: FDPClient
          path: build/libs/FDPClient-${{ steps.vars.outputs.sha_short }}.jar