name: build

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Java setup
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: 8
          cache: "gradle"

      # - name: Set outputs
      #   id: vars
      #   run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Build
        run: ./gradlew build

      # - name: Rename build artifacts
      #   run: mv build/libs/FDPClient-*.jar build/libs/FDPClient-${{ steps.vars.outputs.sha_short }}.jar

      - name: Test
        uses: crazy-max/ghaction-github-pages@v2
      with:
        target_branch: test
        build_dir: /
        keep_history: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: BlackDex
          path: lib/android/sdk/ndk-bundle/*